name: Matrix Example Workflow 

on:
    workflow_dispatch:

jobs:
    Build-Job:
        name: ${{matrix.color}} - ${{ matrix.size}}
        runs-on: ubuntu-latest 
        strategy:
            matrix:
                color: [red, blue, green]
                size: [small, large]
        steps:
            - name: just print the matrix combination in steps.
              run: |
                echo -e "${{ matrix.color }} - ${{ matrix.size }}"
